<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Procat_info;

/**
 * Procat_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Procat_infoRepository extends \Doctrine\ORM\EntityRepository
{

/**
 * @return Procat_info []
 */

}
